### ISSUE TITLE
Epic: IPAM Overhaul

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1032]
### Proposed Changes

Add a proper database-level concept of "parent" and "children" among Aggregates, Prefixes, and IP Addresses data models.  Need to think about how this intersects with tenancy (#130) and VRF membership, as well as things like access control (#982).

### Justification

Allow more straightforward tree traversal, aggregation, filtering, GraphQL querying (#842), etc. Improve UI/API performance (#947).

```[tasklist]
### 🏁 Models Completed/Shippable
- [x] `Namespace`
- [x] `Prefix`
- [x] `IPAddress`
- [x] `VRF`
```
☝️ This means they have their unit tests updated, data migrations implemented (as far as #3681 is concerned), and functional UI/UX. Stories to implement them should be linked below 👇 .

```[tasklist]
### TODO
- [ ] #3424
- [ ] #3681
- [ ] https://github.com/nautobot/nautobot/issues/3748
- [ ] #3465
- [ ] #3634
- [ ] #3635
- [ ] #3636
- [ ] #3637
- [ ] #3536
- [ ] https://github.com/nautobot/nautobot/issues/3682
- [ ] #2916
- [ ] https://github.com/nautobot/nautobot/issues/4096
- [ ] https://github.com/nautobot/nautobot/issues/3935
```

```[tasklist]
### Model Unit Tests
- [ ] https://github.com/nautobot/nautobot/issues/3683
- [ ] https://github.com/nautobot/nautobot/issues/3684
- [ ] https://github.com/nautobot/nautobot/issues/3685
- [ ] https://github.com/nautobot/nautobot/issues/3686
- [ ] https://github.com/nautobot/nautobot/issues/3687
- [ ] https://github.com/nautobot/nautobot/issues/3688
```

```[tasklist]
### Documentation
- [ ] https://github.com/nautobot/nautobot/issues/3689
- [ ] https://github.com/nautobot/nautobot/issues/3690
```

_For linking purposes:_
### Epics
- [x] #1362
- [x] #3302
- [ ] #3244
- [x] #2915
- [x] #1673
- [ ] #2403

**Comment by itdependsnetworks** [comment]
Some thoughts and use cases I wanted to document

* I have a lot of public and private IPs
  * In order to get to my 10 space, I need to scroll through hundreds of low numbered IP space
  * The search is generally not logical to the mental models I have, and drilling down in containers is helpful
* Parent child relationships are important, but high level buckets would be great as well, such as:
  * Public/Private
  * Tenant 1, Tenant 2, etc.. (it's clear that there exists the tenant metadata and search, but this adds to confusion when viewing data)
* Buckets are useful to allow minimal amount of clicks to get to data and adds to the user experience
* Buckets are useful to allow overlapping IP space be better organized, such as with the aforementioned Tenants 
* Containers or supernets are often different then subnets and having that well defined and potentially strictly enforced is useful
  * Subnets are "observable", meaning you can generally find the subnet in a configuration
  * Containers are not often observable and are used for mental models (my EU-Voice prefex is 10.100.0.0/16 vs my AM-Voice is 10.200.0.0/16) and route aggregation (which is bound to the subnet mask lengths)


I think having a tree relationship of Folder (or bucket) -> Container (or supernet) -> Subnet would be desired 

```
.
├── private
│   ├── data
│   │   ├── 10.0.0.0_16
│   │   └── 10.10.0.0_16
│   └── voice
│       ├── 10.100.0.0_16
│       └── 10.200.0.0_16
└── public
    ├── 2.2.2.0_30
    ├── 2.2.3.0_28
    └── 4.0.0.0_28

```

**Comment by glennmatthews** [comment]
One potentially interesting wrinkle to consider is the case of link-local addresses. These would not necessarily be unique even within a given VRF scope.
