### ISSUE TITLE
Feedback Button in Left-Hand Sidebar

### ISSUE THREAD

**Issue by nasa931** [nautobot/nautobot#1175]
As a Nautobot User,

I want to have a "Wish" or "Feedback" button or hyperlink on the footer of every page of the Nautobot UI,

So that I can provide instant feedback on a thought or idea that I have on the Nautobot experience, such as ideas for a new or improved feature, feedback on recent changes to the experience, etc...

I will know this is done when I can use the requested "Wish" or "Feedback" button feature as described above.

## Acceptance Criteria

- A link is present in the footer which directs the user to: https://github.com/nautobot/nautobot/issues/new/choose

---

```[tasklist]
### TODO
- [x] A modal form can pop up to prompt a user to enter free form text to submit to https://nautobot.cloud/api/nautobot/feature-request/
- [ ] Form submission collects user agent, view name (not full path or route), and installed Nautobot version
- [x] A config setting `FEEDBACK_BUTTON_ENABLED` exists (default enabled) to control whether the button/link to open the modal is displayed
- [x] Support an optional input of email address
- [x] Browser sends the request directly, CORS may be an issue
```

Payload:

```json
{
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9",
  "description": "Please allow me to add custom data models in the UI.",
  "view_name": "home_page",
  "nautobot_version": "v1.5.16"
}
```

**Comment by matt852** [comment]
An idea for initially tracking these requests could be posting them to a private Slack channel.  We could then parse through the ideas and open GitHub issues directly as needed.

We may be able to use an API gateway as a relay for this, like in AWS.  The caveat to this idea is Nautobot would require outbound HTTPS access, where some organizations may block it (unless they use their own API gateway).

This could ideally be toggled on/off in the configuration.

**Comment by lykinsbd** [comment]
Potential architecture for this in my mind would be similar to the below.

# Nautobot UX

1. User clicks feedback button
2. Feedback box/form appears
3. Populate feedback
4. Click Submit
5. Thank you notice appears

# Underlying  process

## Nautobot side

1. Form submission triggers Nautobot Job `feedback_reporting_job`
2. Nautobot Job checks configuration for `enable_feedback_reporting` or similar config value
    1. If `enable_feedback_reporting` == False: silently end job and log a message at an appropriate verbosity level with the drop.
    2. If `enable_feedback_reporting` == True: carry on my wayward son
3. Post payload to `feedback.nautobot.com` a CNAME to an AWS API gateway
    1.  If `repsonse.ok` == False, silently end job and log a message at an appropriate verbosity level with the failure
    2. Else log a message at the appropriate verbosity of the success

## Server Side

1. AWS API Gateway receives request, passes to a Lambda function
2. Lambda function is a dead simple slack bot, and it posts feedback into #nautobot-feedback Slack channel
3. Lambda function (or another) watches every hour for a specific emoji response to the message
   1. If emoji == 👍🏻 : it grabs the comment and drops it into a Postgres DB for retention and categorization/reporting (keeping it in Slack for posterity)
   2. If emoji == 👎🏻 : it drops the comment, does not add it to the DB (and maybe deletes the message from slack?).
 
---

Thoughts?

**Comment by lampwins** [comment]
I'll throw out that [Jira Issue Collectors](https://support.atlassian.com/jira-cloud-administration/docs/use-the-issue-collector/) work really well here. Basically, we embed a link to the collector, which is hosted publically by jira and creates issues directly in our backlog where we can triage them.

Collectors can be customized and the embed can include the ability to provide context about where the user came from (what page, what they were doing, etc).

We don't have to host anything and Nautobot doesn't have to talk to the internet.

**Comment by lykinsbd** [comment]
@lampwins I like that, not re-inventing the wheel and what not. 🎉 

In order to hit the Jira collector, Nautobot would still need internet access yes?

**Comment by lampwins** [comment]
Nope, it's just an embedded form that posts to jira, so it is entirely browser-based. There is even a simple version which is just a link to the form, hosted by jira.

**Comment by lykinsbd** [comment]
What in the serverside-JS-magic is this!? :D That's awesome!

**Comment by glennmatthews** [comment]
Would a button that simply links to https://github.com/nautobot/nautobot/issues/new/choose meet this requirement?
