### ISSUE TITLE
Drop Support for Python 3.6, Add Support for Python 3.10

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1268]
### Environment
* Python version: 3.7-3.10
* Nautobot version: 1.X

### Proposed Functionality

This would drop support for Python 3.6 as it will soon be EOL and add support for Python 3.10.

Several recent CVEs have forced split dependency pinning due to them no longer supporting Python 3.6:
- Celery: https://github.com/nautobot/nautobot/issues/1238
- Pillow: https://github.com/nautobot/nautobot/issues/1267

This ultimately leaves installations using Python 3.6 vulnerable although being on the latest version.

### Use Case

All installations.

### Database Changes

Unknown at this time.

### External Dependencies

Unknown at this time.

### TODO

- [x] Add Python 3.10 support (#1255)
- [x] Move default container image to 3.7 (#1252)
- [x] Drop Python 3.6 support

**Comment by bryanculver** [comment]
Adding Python 3.10 support is addressed in https://github.com/nautobot/nautobot/pull/1255.

**Comment by jathanism** [comment]
In my not-even-remotely-humble opinion, given the fact that Python 3.6 is EOL, and we keep running into issues related to 3rd party packages dropping support for Python 3.6, I would say the v1.3.0 milestone is the time to drop support for 3.6 and formally add support for 3.10.

This situation where we are fixing security bugs that exclude Python 3.6 is not a good one to be in, especially for any users out there where this may present Nautobot as an attack surface. We don't want that on our collective consciences.

**Comment by jvanderaa** [comment]
I fully support having the next version of Nautobot whether that is 1.3 or 2.0 drop support for Python3.6. But to me if this project is going to be run on SemVer whatever version drops support for Python3.6 is a breaking change in several deployments. It will need to be a 2.0 release IMO.

**Comment by jvanderaa** [comment]
At that point, is there harm moving 1.3 milestone items to 2.0.0. If there are other breaking changes, it would then just move forward to 3.0 pretty quick.

**Comment by glennmatthews** [comment]
@jvanderaa Asking sincerely - what do you see as the difference between "1.3.0 is out but does not support your Python version, you can't install it unless you upgrade Python" and "2.0.0 is out but does not support your Python version, you can't install it unless you upgrade Python"?

**Comment by jvanderaa** [comment]
For a previously supported version of Python, dropping of said supported Python version support is a breaking change. If the project is following SemVer, then the breaking change should cause a major release is my thought. I'm not jumping on any swords for said scenario. 

The same could be said of why does the next version need to be 1.3.0 since it is a version number. 2.0.0 is also a version number.

**Comment by smk4664** [comment]
I disagree a little, since the change does not include any code that causes breaking changes. Just changing a dependency. Like any of our other dependency changes.

**Comment by smk4664** [comment]
Going by Semver, a dependency change without a public API change doesn’t necessitate a major version bump.

https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by alextremblay** [comment]
Does dropping python 3.6 constitute a breaking change?

I'm not so sure. As I understand it, a breaking change is a change in one part of a system which causes other parts to fail. 

In python, a breaking change is a change which causes software to fail or significantly alter its behaviour once it's been updated, right?

Dropping python 3.6 support doesn't mean existing Nautobot installations will fail after they update, it just means they will no longer receive updates

At least, that's my interpretation

**Comment by jathanism** [comment]
One thing to consider is that [Python 3.6 is the default on RHEL 8](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8-3#python_3). While certainly there are questions about why RH would drop a new distribution in 2019 using an already old version of Python, that ship has sailed. 

If we are to drop support for Python 3.6 pre-v2, we will need to consider impact and/or migration paths for users of RHEL 8, which is currently the latest stable RHEL.

**Comment by alextremblay** [comment]
That is a good point. Thankfully, RHEL provides `python38` as a standalone package, allowing users to install python 3.8 alongside the default distribution. The solution there could be as simple as adding a note to the documentation for RHEL users, no?

**Comment by bryanculver** [comment]
Closed with #1454
