### ISSUE TITLE
Prefix Type

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#1362]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.5

### Proposed Functionality

Proposed to add a `type` field to better handle difference Prefix types, rather than holding them in the status field. Today if one wants to have a status on a prefix of active/standby/maintenance/retired or other and is also a container, then the field cannot be changed to reflect the status of the Prefix. Container and pools are "types" of prefixes, and should be it's own type.

### Use Case

Proposed to add a `type` field to better handle difference Prefix types, rather than holding them in the status field. Today if one wants to have a status on a prefix of active/standby/maintenance/retired or other and is also a container, then the field cannot be changed to reflect the status of the Prefix. Container and pools are "types" of prefixes, and should be it's own type.

### Database Changes

* Addition of prefix_type field
* Change of handling on code of prefix status to prefix types

Likely some more changes than just this.

### External Dependencies

None

Referenced in #1309 for discussion.

### TODO

- [x] Add enum property `type` of values: "Network" (the default), "Container", and "Pool"
    - "Aggregate" is a top-level "Container"
        - This will collapse the Aggregate model into a Prefix of type "Container"
    - Any existing prefix that is marked both "Container" and "Pool" in the current setup, "Pool" takes precedence
- [x] Update usage calculation to use the `type` to influence logic for calculation
    - [ ] Split out into `get_prefix_utilization` and `get_ip_address_utilitization`
- [x] Remove `is_pool` field and `container` status

**Comment by martin-networker** [comment]
The thing that container as a status prevents from setting real status to the prefix is one problem.

Second issue is that Nautobot can't properly determine the utilization of a prefix if it is a container.
For example, if prefix 10.1.1.0/24 is a container and has two child prefixes 10.1.1.0/25 which is utilized on 100% and 10.1.1.128/25 which is utilized on 2%, the parent prefix 10.1.1.0/24 shows utilization of 100% instead of 51%.
This leads to a problem of finding available prefix space.
As searching of free prefix is quite difficult in Nautobot we have a job to do that. Unfortunately this job does not work in all cases because of this false utilization enumeration.

**Comment by bryanculver** [comment]
Closed with #3211

**Comment by bryanculver** [comment]
Closed via #3211. Aggregate collapse moved to #3302
