### ISSUE TITLE
Assert that `FilterSet` filter fields are law and derive forms from them automatically

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1483]
### Proposed Changes

I propose that we refactor ALL `FilterSet` objects to be authoritative for object filtering as  a superset of all desired object fields or custom filters (e.g. Boolean membership tests). Internally FilterSet objects generate their own `Form` class used for validating that incoming query filtering parameters are valid. When `filterset.is_valid()` is called, this in fact internally calls `filterset.form.is_valid()`. Additionally the validated data for the filtered queryset is provided by the internal `filterset.form.cleaned_data`. 

So: The complete proposal is asserting that filtersets are law, and filter forms are just generated from the filtersets and have their desired fields reduced at render time using something defined on the model meta e.g.`Device.Meta.ui_filter_fields = [...]`. And then we eliminate all custom `FilterForm` classes in exchange for model metadata paired with factory methods to generate filter forms when they are needed, derived from the filter sets. 

There would need to be assertion that any given filter field on a `FilterSet` class must be of the correct type (e.g. multiple-choice) and that the field it emits for the UI filter form is also of the correct type.  **Any custom type coercions of filter fields on `FilterSet` classes would then become the exception and not the norm**. 

Additionally this would eliminate the need for bespoke `FooFilterForm` classes because **we would just use the form already generated by the `FilterSet` internally** and merely reduce down the fields used at render time.

There would likely be some other improvements to gluing model objects to their `FilterSet` class. For example consider how often we see this pattern in `FilterSet` classes:

```python
    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        return queryset.filter(
            Q(name__icontains=value)
            | Q(slug__icontains=value)
            | Q(description__icontains=value)
            | Q(content_type__app_label__icontains=value)
            | Q(content_type__model__icontains=value)
        )
```

What if we had another model `Meta` attribute called `filter_search_fields`, such as:

```python
class MyModel(PrimaryModel):
    class Meta:
        filter_search_fields = ["name", "slug", "description", "content_type__app_label", "content_type__model"]
```

And then there could be a generic `search` method on `BaseFilterSet`:

```python
    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        query = Q()
        for search_field in queryset.model._meta.filter_search_fields:
            query |= Q(**{f"{search_field}__icontains": value})

        return query
```

### Justification

It takes too much code to introduce new models, requiring even more overhead when refactoring or maintaining the core code base. Additionally the current implementations are rife with edge-cases and lack of uniformity.

In the current 1.x release train there is NO cohesion between `FilterSet` and `FilterForm` classes. There is incongruence in many cases between the filter field type and the UI form field type which is used for filtering. This makes dynamically leveraging filtersets or forms near impossible without some time-intensive metaprogramming.

These gaps were exposed when trying to implement the `DynamicGroup` feature (#1425). To be able to extend this feature to more model objects, we will have to fix the way we manage filtersets and filter forms, while also reducing boilerplate and streamlining both core and community developer workflows.

### Acceptance Criteria

- [ ] FilterSets contain a complete set of fields to filter the associated model
- [ ] FilterForms should be able to be derived from FilterSets
- [ ] A generated FilterForm should be ultimately usable by the end user (generating an input field for every `field__lookup_expression` is way too verbose).

### TODO

- [x] #1606
- [x] #1607
- Filtering UI/UX Enhancements
    - [x] #1608
    - [x] #1998
- Add Missing Fields to Existing Filter Sets
    - [x] #1729
    - [ ] #1730
    - [ ] #1732
    - [x] #1731
    - [x] #1733
    - [x] #1734
    - [x] #1735
- [x] #1736
- [x] #1737

### Blocking

- [x] #1822

**Comment by itdependsnetworks** [comment]
This seems to me like an extension of #973, does it make sense to add these details there and close this issue?

**Comment by jathanism** [comment]
> This seems to me like an extension of #973, does it make sense to add these details there and close this issue?

Thanks @itdependsnetworks, similar yet different since it's more of a line item in the bigger picture. Kind of seeing the linked issue as an epic and each of the discrete issues for views, serializers/forms, filtersets each as distinct stories.

**Comment by itdependsnetworks** [comment]
Going to close in favor of #973
