### ISSUE TITLE
Jobs Overhaul: Implement database backend for Celery results

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1622]
### Proposed Changes

I propose that we replace the existing implementation of how [`Job`](https://github.com/nautobot/nautobot/blob/main/nautobot/extras/models/jobs.py#L65) classes interact with Celery to feed state changes to [`JobResult`](https://github.com/nautobot/nautobot/blob/main/nautobot/extras/models/jobs.py#L371) objects. This is what I have been referring to the "Job result sandwich". 

We should implement the [database results backend](https://github.com/celery/django-celery-results/blob/master/django_celery_results/backends/database.py#L29) (or a subclass of it) provided by [`django-celery-results`](https://github.com/celery/django-celery-results), which also includes a [`TaskResult`](https://github.com/celery/django-celery-results/blob/master/django_celery_results/models.py#L18) model that is effectively an analog of our `JobResult` object. With some adaptation, we could marry the two.

### Justification

Currently we are leveraging the [default Redis results backend](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L187) for Celery and have some complicated logic inside of the [`nautobot.extras.jobs.run_job()`](https://github.com/nautobot/nautobot/blob/main/nautobot/extras/jobs.py#L995) Celery task to feed state changes back into the `JobResult` object. We have encountered numerous issues in maintaining parity between what's happening on the Celery message bus with the task state vs. the `JobResult` state that gets reflected in the web UI.

Moving to a database results backend would allow for the backend to manage the state transitions and we could eliminate all of the bespoke code required to manage this inside of the complicated `run_job()` task, providing a much more reliable tracking of task transitions being reflected in the `JobResult`. Because this is an officially supported methodology within the Celery core, it's also reducing the technical debt for such a critically important feature to Nautobot.

Finally, this also aligns the persistence of Celery task results into a central location vs. having overlap between task result state that may or may not persist in Redis, and Job state that absolutely persists in the database.

Consider the desire that this should solve things like:

- [x] #633.

### Actions/Checklist

- [x] #2993
- [x] #3085
- [x] #3228
- [ ] #3229
- [x] #3087
- [x] #3088
- [x] #3089
- [x] Update Git Repo Sync, `runjob` management command (#3545)
- [ ] Update Job Hooks, Job Buttons to account for new enqueueing methods
- [ ] See about eliminating `scheduled_job_handler`, altho since that’s internal it’s less scary and may be able to live and could just be used as a dispatcher of a Job's Celery task
- [ ] Custom statuses or data migration for name changes to Job Result status fields to align with those of Celery

**Comment by smk4664** [comment]
I currently use django-celery-results with the database results backend and I love it.  I just thought I would add my two cents.

**Comment by bryanculver** [comment]
Should this be looked at in scope of this epic: https://github.com/nautobot/nautobot/issues/1383
