### ISSUE TITLE
IPAM Overhaul: Prefix-IP Address Parent Concrete Relationship

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1673]
```[tasklist]
### TODO
- [x] https://github.com/nautobot/nautobot/issues/3464
- [ ] https://github.com/nautobot/nautobot/issues/3465
```
- [x] #3681
- [x] #3688 
---
### As ...

Austin - Network Automation Engineer

### I want ...

The IP Address model to have a concrete foreign key relationship to the Prefix model

### So that ...

Lookups for address containment can be optimized, and so that I can ensure proper prefix ownership in the case of duplicate address space.

### I know this is done when...

- A nullable foreign key `parent` is added from the IP Address model to the Prefix model.
- This relationship can be manipulated in the UI and API
- Existing installs have the relationship populated via the logic defined in today's `annotate_tree()` method, so maintain compatibility with the current logic.
- In v1.4 existing UX pertaining to the deletion of prefixes and modification of prefix address space (sub/super-netting) is maintained. If this logic should be changed, that will occur in v2.0.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Add a new nullable `parent` FK from the IP Address model to the Prefix model and populate it via a data migration.

### External Dependencies

None

**Comment by lampwins** [comment]
This is a unit of #1032 and has been identified as being doable in 1.4.

**Comment by jathanism** [comment]
I am not sure if this is the right place for this, but I think we should also make `family` (or `ip_version`) a concrete field on IPAM models instead of a derived query/method field so that family-based filtering is even more efficient and can be indexed.

**Comment by bryanculver** [comment]
Discussion Notes (not all being done in this issue)

**This Story**
- [ ] Add Required FK from IPAddress to Prefix
    - Schema will require an object to exist 
    - "Global" prefixes created for "Global" namespace
- [ ] The view/form
    - If you provide a prefix, find the closest parent
    - If you don't provide a prefix you must provide a namespace
    - UI shouldn't need to show the prefix, as that parenting is enforced to be correct, but should show namespace
- [x] Remove FK to VRF from IPAddress (already in Namespace alpha)
- [ ] Add `ip_version`


**Other:**
- [ ] Should `host` be modifiable?
- [x] Solve loopback problem:
    - Parent prefix is likely very large
    - As-configured is `/32`
- [ ] Ditch Broadcast?
- [ ] Ditch Prefix_length?
    - Use IP Address type to hint at configured mask
- [ ] Revisit "Global" as name for "global" namespace (ie "Default")
