### ISSUE TITLE
Remove django-cacheops dependency/usage

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1721]
### As ...

Nelly - Network Engineer

### I want ...

To have confidence that the Nautobot UI and API are accurately showing me data as it _is_ in the database, not as it _was_ in the past. 

### So that ...

I will not be shown outdated information that misleads me as to what the current state of the database is, such as can be seen in #1627.

### I know this is done when...

- [x] Nautobot no longer uses `django-cacheops`
- [ ] The `invalidate` mgmt command is removed
- [ ] Nautobot overall performance is acceptably similar to where it was when cacheops was still in use
- [ ] Issues such as #1627 are no longer seen

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

N/A

### External Dependencies

Remove `django-cacheops` dependency; shouldn't add any new dependencies.

## TODO

- [ ] Blocked by #1633
- [ ] Remove any stray `prefetch_related` that could be moved to `select_related` that wasn't already addressed in #3112 
- [ ] Remove Cacheops

**Comment by bryanculver** [comment]
We need to be mindful of how to not regress on #1515.

We leveraged `cacheops` because if it's file-based caching for the problems it tried to solve there.

**Comment by jathanism** [comment]
One option is that we could leave `cacheops` as a dependency for using `@cacheops.file_cache.cached()` but disable it for use in queryset caching

Another would be to switch to another library that supports disk caching. One of the newer ones [`DiskCache` has built-in support for Django caching framework](https://grantjenks.com/docs/diskcache/tutorial.html#djangocache). A decorator pattern would still need to be considered.

**Comment by bryanculver** [comment]
Let's also see if this resolves #1723, #1694

**Comment by bryanculver** [comment]
We will likely need to keep the dependency in the short term due to being leveraged by plugins, but ultimately rip out in the future.

**Comment by jathanism** [comment]
Last comment is that we also need to consider the monkey-mixin pattern, to carry forward into v2 when we ditch it. We could forklift the requisite code and ditch cacheops and of course provide attribution in the `NOTICE` file.

**Comment by glennmatthews** [comment]
Is there further work required for 1.5 or can we close this now that #2415 is merged?

**Comment by bryanculver** [comment]
Transitioned #2415 to be the 1.5 milestone record and moving this to be the 2.0 work of removing cacheops entirely.

A majority of the work wasn't done in #2415

**Comment by jathanism** [comment]
Remaining work to wrap this up, sorted by filename:

```
nautobot/circuits/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related (for tags it should stay)
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/circuits/models.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/circuits/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/core/api/authentication.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/core/api/views.py
- # v2 TODO(jathan): Revisit whether this is still valid post-cacheops. Re: prefetch_related vs.
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/core/authentication.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/core/constants.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/core/settings.py
- "cacheops",  # v2 TODO(jathan); Remove cacheops.
- # v2 TODO(jathan): Remove all cacheops settings.

nautobot/dcim/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (content_types should remain
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags because it is m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags because it is m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (extap tags because it is m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)

nautobot/dcim/forms.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/dcim/models/racks.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/dcim/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/extras/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related (except the
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/extras/homepage.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/extras/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/ipam/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tgs: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)
- # v2 TODO(jathan): Replace prefetch_related with select_related (except tags: m2m)

nautobot/ipam/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/tenancy/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related (it should stay for tags)

nautobot/tenancy/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/users/admin.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related (these # might be m2m)

nautobot/users/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_relatedn

nautobot/utilities/tables.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/virtualization/api/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/virtualization/forms.py
- # v2 TODO(jathan): Replace prefetch_related with select_related

nautobot/virtualization/views.py
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related although this one may be
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
- # v2 TODO(jathan): Replace prefetch_related with select_related
```

**Comment by jathanism** [comment]
```
nautobot/core/tests/nautobot_config.py
- CACHEOPS_ENABLED = False  # 2.0 TODO(jathan): Remove me.
```

**Comment by bryanculver** [comment]
Blocked by #1633

**Comment by bryanculver** [comment]
Closed with #3645
