### ISSUE TITLE
Jobs - Grouping as Meta Field

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#2249]
### As ...

Austin - Network Automation Engineer

### I want ...

To have the ability to define a job grouping within the job meta data

### So that ...

I can logically group my jobs without having to use individual files for each job.

### I know this is done when...

- Groupings are available to Jobs
- The groupings can be defined within the `Meta` or other means within the Job Class itself.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- ?

**Comment by lampwins** [comment]
I confirmed the group can be overridden in the Job class record in the DB (available in 1.3). Does this suffice, or is it a must to be able to define this in `Job.Meta`?
![Screen Shot 2022-08-17 at 10 18 41 PM](https://user-images.githubusercontent.com/1297132/185278650-95db7b3b-491d-41ec-91cc-9adf30c2005d.png)

**Comment by jvanderaa** [comment]
For this feature request we would like to be able to define it in code. So that as jobs get promoted from development to integration to production a consistent experience is had.

**Comment by jvanderaa** [comment]
It does not need to be done in Meta specifically, but a method to change within the Jobs.py file type action.

**Comment by glennmatthews** [comment]
The below appears to work locally - no update to core required, though we could certainly import this into core as a standard feature:

```python
from django.utils.functional import classproperty

class MyJob(Job):
    @classproperty
    def grouping(cls):
        return getattr(cls.Meta, "grouping", super().grouping)

   class Meta:
       grouping = "My custom grouping"
```

You could also always just go with:

```python
from django.utils.functional import classproperty

class MyJob(Job):
    @classproperty
    def grouping(cls):
        return "My custom grouping"
```

**Comment by jvanderaa** [comment]
@glennmatthews does this have a documentation reference as well?

**Comment by glennmatthews** [comment]
I closed it because of the working example provided above. No code/documentation change was done.
