### ISSUE TITLE
Device role font color customization

### ISSUE THREAD

**Issue by jlixfeld** [nautobot/nautobot#2340]
### As ...

Nelly - Network Engineer

### I want ...

to be able to customize the font color for a device role color

### So that ...

text is more easily readable in dark mode against certain device role color selections

### I know this is done when...

there is an option to select a font color when creating a device role

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Unsure

### External Dependencies

Unsure

### TODO

- Ignore filter inversion for labels (Roles, Statuses, Tags, etc), buttons.

**Comment by lampwins** [comment]
We should look at just not inverting labels and buttons.
