### ISSUE TITLE
Supply .Meta.verbose_name_plural for all models

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#2394]
### As ...

Austin - Network Automation Engineer

### I want ...

all the models present in Nautobot to have a `verbose_name_plural` field under `Meta`.

### So that ...

I can use this field to build URLs when I only have the model name in singular, needed for example when syncing relationship associations with SSoT.

### I know this is done when...

There is a `verbose_name_plural` field under the `Meta` class for all of the models.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by Kircheneer** [comment]
Please let me know if this approach is not idiomatic in Django and I have some other way of achieving this. Thanks!

**Comment by Kircheneer** [comment]
And this would be an API that we can safely consume, although it is prefixed with an underscore?

**Comment by bryanculver** [comment]
> And this would be an API that we can safely consume, although it is prefixed with an underscore?

Yes, although it does feel weird I agree: https://docs.djangoproject.com/en/3.2/ref/models/meta/

**Comment by bryanculver** [comment]
Already available via Django `_meta` API and documented as such.
