### ISSUE TITLE
IPAM Overhaul: Assign IP Address to Multiple Interfaces

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#2403]
```[tasklist]
### TODO
- [x] #3190
- [x] #3236
- [ ] https://github.com/nautobot/nautobot/issues/3411
```

```[tasklist]
### High Priority
- [ ] #3634
- [ ] #3635
- [ ] #3636
- [ ] #3637
- [ ] https://github.com/nautobot/nautobot/issues/4100
- [ ] https://github.com/nautobot/nautobot/issues/4104
- [ ] #3536
```

---
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to assign one IP address to multiple interfaces/devices.

### So that ...

We can assign anycast and other shared IP addresses to all interfaces/devices which has this IP address assigned instead of assigning this IP.

### I know this is done when...

Reason for request:
In our infrastructure we use anycast IP addresses extensively. For example in on DC around two hundred switches share about 40 anycast IP addresses. Another case is for NVE interface switches in VPC cluster has to share one IP so in every VPC cluster two switches share one IP.

Current Nautobot options:
  1) Assign shared IP address to one device:
  	 This will be incorrect information and it will lead to confusions and cause mistakes.
  2) Create a custom field for the interface object that points to the IP address object:
     This will not give us any connection between IP and interfaces. User or script would have to go through all interfaces of all devices to find out where is IP assigned which makes it unusable.
  3) Create a One-To-Many relationship which will connect IP address to multiple interfaces:
     IP address is not seen in Interfaces view (if you open Device and switch to tab interfaces) you must open every interface to find where it is assigned.
	 IP address does not have assignment (Operational Details > Assignment).
	 This means the relationship is not visible from Interfaces view nor from IP address view.

Possible solution:
  Change assignment of IPs from one-to-one to one-to-many. This would be a breaking change and require a database change.
  In GUI it would be great to keep the current functionality and create condition:
    a) if IP is assigned to only one Interface:
	in Operational Details > Assignment it will show the one Device directly (just like it is now)
    b) if IP is assigned to more than one Interface (or maybe it can be based on Role so if IP Role is Anycast/Shared/etc.):
	Operational Details > Assignment will show something like Relationship is showing. Parameter interfaces and value will be link (x interfaces) which would open new window IP Address Associations (similar to Relationship Associations).
  If the condition would cause difficulty the b) option would be sufficient.
  If you have different idea how to achieve this we can discuss it in comments.

### Optional - Feature groups this request pertains to.

- DCIM
- IPAM
- Virtualization

### Database Changes

Yes: change of current IP address model.

**Comment by bryanculver** [comment]
Medium to low priority issues have been moved to "IP-Interface M2M Enhancements" epic in Zenhub. To be prioritized and committed to accordingly.

Closing as #3636 is in flight and last open issue of this epic.
