### ISSUE TITLE
Epic: Collapse Region and Site models into Location

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2517]
### As ...

Dan - Data Owner

### I want ...

To be able to represent my organization's specific organizational structure, which may not fit into the current specific Region > Site > Location paradigm. For example:

- I want to have geolocation and contact info on my hierarchy of "regions" or "locations", rather than only at the flat "site" level
- I want to have arbitrarily nested "sites"
- I want to be able to assign a VLAN to a "region" rather than a "site", a device to a "room" rather than a "site", etc.

### So that ...

My data model reflects my organizational reality, rather than needing to fit a square peg into a round hole.

### I know this is done when...

- Most likely, the Region, Site, and Location models are merged together, most likely into a single combined Location/LocationType model that supports all relevant features of the previous separate models.
- Nautobot provides migrations or scripts that make it straightforward to move my existing Region and Site data into a new Location hierarchy without data loss.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [X] Misc (including Data Sources)
- [X] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Absolutely will involve database changes.

### External Dependencies

- django-tree-queries
- others?

## TODO

- [x] #2954
- [x] #2955
- [x] #2956
- [x] #2957
- [x] #2958
- [ ] #3374 
- [ ] #3386 
- [ ] #3387

**Comment by bryanculver** [comment]
- [ ] #3386 
- [ ] #3387 

Aren't specific to Site, Region collapse.

- [ ] #3374 

The failure of reverse migration we need more context on: You shouldn't be prevented from deleting the app with doing a `zero` and changing (or not changing) data you're going to delete anyway shouldn't cause reverse to fail.


Closing as complete.
