### ISSUE TITLE
Remove dependency on django-cryptography (and associated Git repository token storage)

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2521]
### Proposed Changes

`django-cryptography` is a thorn in our side due to https://github.com/georgemarshall/django-cryptography/issues/56 causing our database to break whenever `SECRET_KEY` is changed. (See #445, etc.)

We also need to remove the `token` field on GitRepository and its associated functionality, leaving Secrets as the only supported way to provide authentication credentials for a Git repository.

### Justification

We shouldn't be storing security-related data in Nautobot's database anyway, and since 1.3.0 we have Secrets as the more correct way to handle this sort of information.

## TODO

- [x] Remove need for `django-cryptography`
- [x] Review earlier migrations for no longer needing this dep
- [x] Provide migration guide that this functionality will no longer exist and they must move to using Secrets (and how to set that up)

**Comment by glennmatthews** [comment]
Implemented in #3451
