### ISSUE TITLE
Epic: Jobs Improvements (2.X)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2724]
This will likely extend through the 2.1-2.3 milestone but tracking a "super epic" here.

## TODO
- [x] #3352
- [ ] #2830
- [ ] Review plugin API to create new tab for specific job results page (storing tab data in database), e.g. stdout, command outputs, etc.
- [ ] Job code can be mismatched between Nautobot and its workers (pain for both development and production)
- [ ] Chain Job Executions
    - If succeed, call X
    - If fail, call Y
- [ ] Job Multi-threading

**Comment by brobare** [comment]
Another one that would be nice would be the ability to render out HTML at the end of a job execution. Something along the lines of how `template_content.py` works currently:

```
class JobWithOutput(Job):
    def run(self, data, commit):
        do things
        output_tab(data_from_job_run)

    template_name = "example_plugin/panel.html"
    def output_tab(self, data_from_job_run):
        return self.render(
            self.template_name,
            extra_context={
                "results":  data_from_job_run,
            },
        )
```

And that would get called at the end of the job to "fill in" the `output` tab.
