### ISSUE TITLE
Epic: Jobs Enhancements (Future)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2725]
**Ideas**

- [ ] #884 
- [ ] Enhancing/constraining Job Form inputs shouldn't require overloading the whole form
- [x] #1598 
- [ ] Create a "light" or shim-layer plugin that interfaces with Ansible AWX/Tower similar to the Nornir plugin that enables Golden Configuration
- [ ] Review what a Job can do (modify database) based on user permissions on those specific tables
- [ ] Each job runner is running a full instance of Nautobot which has it's own memory "bloat"
- [ ] #1081
