### ISSUE TITLE
Default Nautobot API Version

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#2799]
### As ...

Austin - Network Automation Engineer

### I want ...

Use the latest features that are offered by the API

### So that ...

* I may get maximum benefit from the latest features.  
* Know when there are small breaking changes vs only when there are major breaking changes

### I know this is done when...

Without setting a header, I get the latest API functionality given I am using the latest version of code.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

N/A

### TODO

- Verify DRF's default behavior when `DEFAULT_VERSION` is `None`, expecting it chooses the latest
- Remove `DEFAULT_VERSION` from `settings.py`
- Make it easier via config and documentation to override "default to latest" behavior

**Comment by bryanculver** [comment]
Allowing a "magic" setting of `latest` as well as a specific version to be provided here: https://github.com/nautobot/nautobot/blob/develop/nautobot/core/settings.py#L195 should suffice. We should by default still fall back to the oldest minor version if not provided.
