### ISSUE TITLE
Interface Redundancy Model

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2825]
A prototype of this exists:

- https://github.com/nautobot/nautobot/tree/prototype/2825-interface-redundancy-groups (via #2621)

---

### As ...

Nelly - Network Engineer

### I want ...

To be able to model interface redundancy strategies (hsrp, vrrp, carp, glbp?, vpc?) 

### So that ...

Multiple interfaces can be grouped together as one logical unit 

### I know this is done when...

I can create an interface redundancy group and relate it to more than one interface.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

New model in dcim

### TODO

- [x] Document use cases for VRRP
- [ ] Document use cases for HSRP
- [ ] Document use cases for CARP
- [ ] Document use cases for GLBP (if in scope)
- [ ] Document use cases for vPC (if in scope)

**Comment by gsnider2195** [comment]
# Example VRRP use case

```
! Router A
interface GigabitEthernet 1/0/0 
ip address 10.1.0.2 255.0.0.0 
vrrp 1 priority 120 
vrrp 1 authentication cisco 
vrrp 1 timers advertise 3 
vrrp 1 timers learn 
vrrp 1 ip 10.1.0.10 
vrrp 5 priority 100 
vrrp 5 timers advertise 30
vrrp 5 timers learn
vrrp 5 ip 10.1.0.50 
vrrp 100 timers learn
no vrrp 100 preempt 
vrrp 100 ip 10.1.0.100

! Router B
interface GigabitEthernet 1/0/0 
ip address 10.1.0.1 255.0.0.0 
vrrp 1 priority 100 
vrrp 1 authentication cisco 
vrrp 1 timers advertise 3 
vrrp 1 timers learn 
vrrp 1 ip 10.1.0.10 
vrrp 5 priority 200 
vrrp 5 timers advertise 30
vrrp 5 timers learn
vrrp 5 ip 10.1.0.50 
vrrp 100 timers learn
no vrrp 100 preempt 
vrrp 100 ip 10.1.0.100
```

## Common Configuration

```
vrrp 1 authentication cisco 
vrrp 1 timers advertise 3 
vrrp 1 timers learn 
vrrp 1 ip 10.1.0.10 
vrrp 5 timers advertise 30
vrrp 5 timers learn
vrrp 5 ip 10.1.0.50 
vrrp 100 timers learn
no vrrp 100 preempt 
vrrp 100 ip 10.1.0.100
```

## Unique Configuration
```
! Router A
interface GigabitEthernet 1/0/0 
ip address 10.1.0.2 255.0.0.0 
vrrp 1 priority 120 
vrrp 5 priority 100 

! Router B
interface GigabitEthernet 1/0/0 
ip address 10.1.0.1 255.0.0.0 
vrrp 1 priority 100 
vrrp 5 priority 200 
```

**Comment by bryanculver** [comment]
We're going to dust the prototype off from #2621. The prototype branch it was merged into needs to be rebased from `develop` and shows some of the early implementation of #2615.

_The data model as-is from #2621:_ https://github.com/nautobot/nautobot/blob/f7b5be33f1d8cb93a2283f7343ffb3a0fe2bb8ae/nautobot/dcim/models/devices.py#L965-L1016


Some changes we need to consider:
- Use `StatusField` instead of `StatusModel` (see: #3785)
- Overload `created` to pre-emptively model 2.0 behavior (see: #2076)
- Change `group` and `groups` fields to `interface_redundancy_group(s)` to be more explicitly
- Drop `slug` (see #2662), URLs use PK, name already unique for 2.0 use with natural keys

**Comment by HanlinMiao** [comment]
Closed by #4177
