### ISSUE TITLE
Jobs Overhaul: Ensure Cruft is Removed/TODOs Addressed

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2853]
### Proposed Changes

```[tasklist]
### Tasks
- [x] https://github.com/nautobot/nautobot/blob/fc6156572d61fa855dcff17abf0cf01a482073d6/nautobot/extras/urls.py#L409-L413 # 2.0 TODO(jathan): Remove this, no existing code references `job_jobresult` but plugins and others may.
- [x] https://github.com/nautobot/nautobot/blob/fc6156572d61fa855dcff17abf0cf01a482073d6/nautobot/extras/urls.py#L432-L437 # 2.0 TODO: JobDetailView should be just JobView, but see below
- [x] https://github.com/nautobot/nautobot/blob/fc6156572d61fa855dcff17abf0cf01a482073d6/nautobot/extras/urls.py#L452-L454 # 2.0 TODO: JobView should actually be JobRunView, but keeping it as-is for backwards compatibility
- [x] Change methods on `BaseJob` to classmethods where appropriate (`as_form_class`, `as_form`, `validate_data`)
```

## Move to comments cleanup
nautobot/extras/api/views.py
- [x] # 2.0 TODO: To revisit this as part of a larger Jobs cleanup in 2.0.

## Move to future housekeeping (non-breaking)
nautobot/extras/models/jobs.py
- [ ] # 2.0 TODO: standardize verbose name for ContentType fields

### Justification

Legacy cleanup.
