### ISSUE TITLE
Correct Existing Natural Keys 2 of 3 [Intermediate] - Conditional Uniqueness

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2908]
Correct or assert existing natural keys on objects where conditional uniquness is a requirement or concern.
---

```[tasklist]
### Tasks
- [ ] **Service:** Unique together: `(device, name)` and `(vm, name)` with natural key `(name, device, vm)`; for duplication use other fields to help add to name uniqueness - 2
- [ ] **Device Type:** A stretch goal is to rename `model` to `name`
- [ ] **Device:** Configurable natural key/unique, default to PK
- [x] **Computed Field:** Make `key` unique
- [ ] **VirtualChassis:** Make `name` unique, reject migration if duplicate (don't want to rename VCs) - 2
- [ ] **ScheduledJob:** Make `name` unique, enumerate if duplicate, update help text and auto-assign name (the uuid) for one-off jobs
- [ ] **JobResult:** Ensure `pk` is called out as the natural key
- [ ] **Job:** (see below)
- [ ] **ExportTemplate:** Move to `unique_together` on just `content_type` and `name`, reject migration if duplicate
- [ ] **ConfigContextSchema** Move to `name` unique, reject migration if duplicate
- [ ] **ConfigContext** Move to `name` unique, reject migration if duplicate
```
---
**Job**
- Relax unique on `name` because it will be make unique together with `grouping`: `unique_together = ["grouping", "name"]`
- Make the natural key `class_path` which is unique
- Other fields (git repository, source, etc) being removed in #765

---

- **VLAN Group:** discussed in #2909
- **Circuit:** Good enough for now with `["provider", "cid"]`
- **Circuit Termination:** Good enough with `["circuit", "term_side"]`
- **Cable:** Good enough for now, just could use some UX improvements for describing it
- **GitRepository** `name` good enough for now

**Comment by bryanculver** [comment]
Remaining stories carved into #3845, #3846, #3847, #3848, #3849
