### ISSUE TITLE
Client-Side UI: Extend React Prototype

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3026]
Draw the rest of the owl time:

- [x] Core rendering HTML content provided by a plugin (see detail view plugin content left-side/right-side) `PluginTemplateExtension.[right/left/full_width]_page `
- [x] Plugin providing additional tabs on object detail view `PluginTemplateExtension.detail_tabs`
- [x] Core view rendering new components provided by a plugin (New, should be available via React)
- [x] Plugin providing buttons in list view (TBD)
    - With what we've implemented for the plugin features above this should be straight forward to implement
- [x] Plugin overriding entire core view `Views.override_views` (assuming Django routing is no longer in play)
- [ ] Plugin's home & config views:
   - `://nautobot/plugins/example-plugin/config/`
   - `://nautobot/plugins/example-plugin/`

**Comment by gsnider2195** [comment]
## Core rendering HTML content provided by a plugin (see detail view plugin content left-side/right-side) PluginTemplateExtension.[right/left/full_width]_page 

- Works similarly to Nautobot 1.x
- No changes for plugin developers
- Plugin template content fetched from django by javascript and loaded into the js ui via the [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) property

## TODO

- [ ] Load all tabs on page load but don't load content until active tab changes

**Comment by gsnider2195** [comment]
## Plugin providing additional tabs on object detail view PluginTemplateExtension.detail_tabs

- Works similarly to Nautobot 1.x
- No changes for plugin developers
- Plugin template content fetched from django by javascript and loaded into the js ui via the [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) property

## TODO

- [ ] Load all tabs on page load but don't load content until active tab changes

**Comment by gsnider2195** [comment]
## Core view rendering new components provided by a plugin (New, should be available via React)

- TODO

**Comment by gsnider2195** [comment]
## Plugin providing buttons in list view (TBD)

- TODO?

**Comment by gsnider2195** [comment]
## Plugin overriding entire core view Views.override_views (assuming Django routing is no longer in play)

- TODO

**Comment by gsnider2195** [comment]
## Plugin's home & config views

- TODO

**Comment by gsnider2195** [comment]
To augment or override core components with React componenets, plugins will export a plugin config constant in `index.js` that works similarly to the django `PluginTemplateExtension` class. Example:


```js
const plugin_config = {
  detail_tabs: {
    "dcim:site": [ExamplePluginDcimSiteTab1],
    "dcim:device": [ExamplePluginDcimDeviceTab1]
  },
  full_width_page: {
    "circuits:circuit": [ExamplePluginCircuitFullWidthComponent]
  },
  view_overrides: {
    "ipam:prefix": {
      "list": ExamplePluginIpamPrefixListViewOverride,
      "retrieve": ExamplePluginIpamPrefixRetrieveViewOverride,
      "update": ExamplePluginIpamPrefixUpdateViewOverride,
      "destroy": ExamplePluginIpamPrefixDestroyViewOverride,
    }
  },
  buttons: {
    "ipam:ipaddress": [ExamplePluginButtonComponent]
  }
}

export default plugin_config
```
