### ISSUE TITLE
Epic: UI Overhaul

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3142]
### Proposed Changes

Draw the rest of the 2.0 UI Owl. We now need to design and implement all of the research from #1566, #3026 (and somewhat #910)

```[tasklist]
### TODO
- [ ] https://github.com/nautobot/nautobot/issues/3691
- [ ] Homepage Views for Schedule Job, Job Approval
- [ ] Leverage more skeletons, loading widgets (render early, update often after mount)
- [ ] Re-introduce plugin extensibility in views (plugin tabs, etc)
```

```[tasklist]
### Project
- [ ] #3203
- [ ] #3237
- [ ] https://github.com/nautobot/nautobot/issues/3330
- [ ] https://github.com/nautobot/nautobot/issues/3331
```

```[tasklist]
### Development Environments & Testing
- [x] #3204
- [ ] #3238
- [ ] #3239
- [ ] Integration Tests: Ensuring the UI and possibly API-"form" can be ensured working together
- [ ] Integration Tests: Ensuring rending of legacy views are still testable
- [ ] Migrating Existing: UI Views as they exist today
- [ ] Migrating Existing: If we move all form-submissions go to the API do many of these go away/get refactored?
- [ ] Migrating Existing: For UI views that stay around ensuring they still work and supported
- [ ] UI 2.0: Copy `asset-manifest.json` using CopyWebpackPlugin instead of run_command
```
  
```[tasklist]
### CI Pipelines  
- [ ] Core: CI Pipelines (enforcing tests, making any packaging requirements for publishing PyPI, etc)
- [ ] Apps (and update Cookie Cutter)
- [ ] User Guides (outside of the getting started that exists today that should be updated as a part of the changes above)
```

```[tasklist]
### Architecture
- [ ] #3240
- [ ] #3241
- [ ] Non-`TemplateExtension` context views need a defined migration strategy, possibly an entire replacement
- [x] Route definitions in the UI
- [ ] Folder structure
- [ ] Naming conventions
- [ ] #3242
- [ ] https://github.com/nautobot/nautobot/issues/3526
- [ ] #3582
- [ ] https://github.com/nautobot/nautobot/issues/3648
```

```[tasklist]
### Components
- [ ] #3205
- [ ] Advanced components / designs patterns
- [ ] Linked form fields aka "field dependencies" (region limiting site, etc)
- [ ] https://github.com/nautobot/nautobot/issues/3373
- [x] Skinny `index.js`, create an App.jsx
- [ ] https://github.com/nautobot/nautobot/issues/2516
- [ ] https://github.com/nautobot/nautobot/issues/3527
- [ ] https://github.com/nautobot/nautobot/issues/3583
- [ ] Dynamic model choice via API in React
```

```[tasklist]
### Basic Views
- [ ] https://github.com/nautobot/nautobot/issues/3528
- [x] List
- [ ] Create/Edit
- [ ] Delete
- [x] Home
- [ ] Bulk-Edit
- [ ] Bulk-Delete
- [ ] Login
- [ ] Error
- [ ] Notes
- [ ] Change logging
- [ ] https://github.com/nautobot/nautobot/issues/2980
- [ ] https://github.com/nautobot/nautobot/issues/3529
```

```[tasklist]
### Extensibility
- [ ] https://github.com/nautobot/nautobot/issues/3712
- [ ] https://github.com/nautobot/nautobot/issues/3711
```

```[tasklist]
### Advanced Views
- [ ] Cable Trace
- [ ] Swagger
- [ ] GraphiQL
```

```[tasklist]
### Documentation
- [ ] Add documentation around using `useDispactch`, `useEffect`, `useSelector`
- [ ] Add documentation around state reducers
- [ ] 
```

### Potential candidates for react form component library

- https://github.com/vazco/uniforms
- https://github.com/react-hook-form/react-hook-form
- https://github.com/final-form/react-final-form
- https://github.com/redux-form/redux-form
- https://github.com/jaredpalmer/formik
- https://github.com/rjsf-team/react-jsonschema-form
- https://github.com/eclipsesource/jsonforms

### Examples of UI schemas

- https://ui-schema.bemit.codes/

**Comment by gsnider2195** [comment]
Potential reverse proxy for local development environment

https://www.npmjs.com/package/express-http-proxy

**Comment by bryanculver** [comment]
Follow-up from #3691 

- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1179652450
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#diff-3efdb02ae49cfbad9f936680d08cd249b0df924462a8e4143a64dbfd2a6ea991R17
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182696165
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182695421
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182693065
- [ ] Review `return <></>`s: https://github.com/nautobot/nautobot/pull/3651/files#r1182670642
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182669913
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#diff-c01e7ae1f8904441f26e96d62f13f94b8c326fdfb71bd9e905790d6f410f5b9bR27
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#diff-9df470b17bd479c30cd4443ed0bf0ab7f07fae2fc38898c06fecba1d1b0c3b95R8
- [ ] Separate function: https://github.com/nautobot/nautobot/pull/3651/files#diff-3b98c6bf3b5474c33bade6236095b68d68344016a2cd773455cdd525a284e3aaR9-R30
- [ ] Decouple object list view components from object table component
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#diff-458c7051c4e43d07a479d6bd045f1742a59b9d42f49b50acb49e8c5bde393cc7R6
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#diff-c9c5c695263f7b51326bfc2a389e86c8002b7aef6f3e3afb8c18fb7f870f7088R7
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182659136
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1179643231
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182655487
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1185507076
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1182648830
- [ ] https://github.com/nautobot/nautobot/pull/3651/files#r1187862426

**Comment by bryanculver** [comment]
- [ ] Need to have a focused discussion around the schema for describing table, detail views
- [ ] Deconstruct https://github.com/nautobot/nautobot/issues/3142#issuecomment-1539052314 into actionable items
- [ ] Login View
- [ ] Prod container doesn't build UI
- [ ] Schedule & approval tabs on homepage need design but don't have in Figma
    - <img width="1714" alt="image" src="https://github.com/nautobot/nautobot/assets/31187/5e94593e-ec51-4515-a6be-fd146db0222b">
- [ ] Tree view on table
- [ ] Icons updated from Figma design, replacing FontAwesome where we can
- [ ]
