### ISSUE TITLE
UI 2.0: Create Build Pipeline for Core (Generates UI on startup/post-upgrade)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3203]
This translates as hiding `npm` behind a management command (e.g. `nautobot-server build`) and then having it as something that can then be called by other commands such as `post_upgrade`. (See similar example from NSoT project embedding this into `setup.py build`: https://github.com/dropbox/nsot/blob/develop/setup.py#L66-L90)

Webpack should be configured to deploy files to the `STATICFILES_DIRS` which defaults to `project-static` in the `js` directory? (See: https://pascalw.me/blog/2020/04/19/webpack-django.html):

> 1. Have Webpack write to a directory in `STATICFILES_DIRS`
> 2. Configure output.publicPath to match Django's `STATIC_URL`
> 3. Don't let Webpack hash filenames (except for chunks, see below)
> 4. Make sure `webpack-dev-server` writes files to disk (so Django can serve them in development)

```[tasklist]
### Tasks
- [x] Create new `build` management command
- [x] Configure web pack to deploy bundles to `project-static/js`
- [x] Assert that `build` is called by `post_upgrade`
```

**Comment by bryanculver** [comment]
Closed with #3306
