### ISSUE TITLE
UI 2.0: Core (& Example Plugin) Development Environment

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3204]
```[tasklist]
### Tasks
- [x] Rebase prototype UI branch (`bsc-port-next-to-react`) from `next`
- [x] Document setup of dev envrionment (modifications to include `npm` as a dependency)
- [x] Docker container for `node` 
- [x] Create an "official" UI 2.0 dev branch
- [x] Fix linting issues in branch
- [x] Review diffs to identify any proof-of-concept code to remove
```

**Comment by glennmatthews** [comment]
Done, see #3285.
