### ISSUE TITLE
Jobs Overhaul: Replace `run_job` with `NautobotTask`

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3228]
- Still need to eliminate `run_job` and move the stuff to `NautobotTask` handler methods
    - Anywhere explicit status changes are being made must go away. We want Celery to make these decisions, along with any explicit calls to `JobResult.save()`, moving those to the `NautobotTask` class or the backend or a mix of both, depending.
    - Review/evaluate `nautobot.extras.datasources.git.log_job_result_final_status` - Can likely be deleted
    - Remove explicit `set_state/save` code from `nautobot.extras.datasources.git.pull_git_repository_and_refresh_data`
    - Review `nautobot.extras.datasources.registry.refresh_datasource_content` to remove explicit `set_state/save` code
- Eliminate the atomic block (#2726) while we're at it.
- Emphasize evolving to the `run()` method being a Celery task once `run_job` is gone, whether we tell users they must decorate it or do so in a metaclass, OR possible even just making the `BaseJob` class a subclass of `NautobotTask` and only registering it in Celery when `enabled=True`. Something like that.

The goal here is to replace `run_job` in exchange for v2 task subclasses. Ideally, v2 `BaseJob` replacement would be a subclass of `NautobotTask` where the `run()` method is still defined. See: https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.run

```[tasklist]
### TODO
- [x] Move `run_job` Logic to `nautobot.extras.jobs.BaseJob` in `before_start` and `after_return` methods
- [x] Register jobs with Celery app directly (instead of via `@nautobot_task` on `run_job`)
- [x] Update `enqueue_job` to call job directly, instead of `run_job`, to accept `JobModel`
- [x] Don't copy over atomic block handler (#2726)
- [x] Update places (Jobs specifically, not Git Repo sync, et all) that call `enqueue_job` for new signature
```

**Comment by jathanism** [comment]
Deep Thoughts™ by Jathan McCollum:

- Basically everyhting in `run_job` prior to inner  `_run_job` would go into the `NautobotTask.before_start` method (See: https://docs.celeryq.dev/en/stable/userguide/tasks.html#before_start)
- And then `Job.post_run` if we want to keep that would basically just be an analog for `after_return` (See: https://docs.celeryq.dev/en/stable/userguide/tasks.html#after_return)

**Comment by gsnider2195** [comment]
Based on research done today it appears that creating a custom celery `Request` will only be beneficial if we want to overload that class's `on_accepted`, `on_timeout`, `on_success`, `on_retry`, `on_failure`, or `on_success` methods. Celery doesn't provide a method of chaining tasks together while using the Request to share state between tasks (example `dryrun=True`).

Example job using `NautobotJobTask`:

```py
class MultiplyJob(NautobotJobTask):
    x = IntegerVar()
    y = IntegerVar()
    dryrun = BooleanVar()
    requires_approval = True

    def run(self, x, y, dryrun):
        result = x * y
        logger.info(f"{x} * {y} = {result}")
        return result
```

Chaining multiple jobs together would look like this:
```py
from nautobot.core.celery import app


task = app.tasks["example_plugin.jobs.MultiplyJob"]
chain(task.s(4, 5, dryrun=False), task.s(3, dryrun=True))()
```

**Comment by gsnider2195** [comment]
> Would a Job author be able to implement their own timeout/success/failure handlers (e.g. to roll back changes in case of timeout or failure) as part of their Job/Task implementation, or is that something that can only be done with a custom Request class?

The celery task class has methods for `before_start`, `on_success`, `on_retry`, `on_failure`, and `after_return` that can be overloaded on the `Job` class. I'm not sure yet if the task class is able to handle timeouts or if that requires a custom request class.

**Comment by gsnider2195** [comment]
The default celery behavior is to store the task args and kwargs on the task result (JobResult). How do we handle sensitive job args?

- Tell job authors to use secrets. Jobs will always store task args and kwargs on the JobResult so if jobs are prompting for sensitive information it will get stored in the database

or

- Figure out how to skip storing the `task_args` and `task_kwargs` on the JobResult

**Comment by gsnider2195** [comment]
> The default celery behavior is to store the task args and kwargs on the task result (JobResult). How do we handle sensitive job args?
> 
> * Tell job authors to use secrets. Jobs will always store task args and kwargs on the JobResult so if jobs are prompting for sensitive information it will get stored in the database
> 
> or
> 
> * Figure out how to skip storing the `task_args` and `task_kwargs` on the JobResult

I was able to filter out sensitive args/kwargs from the JobResult by [setting `argsrepr` and `kwargsrepr` when calling the job](https://docs.celeryq.dev/en/stable/userguide/tasks.html#hiding-sensitive-information-in-arguments). Fixed in https://github.com/nautobot/nautobot/pull/3483/commits/aa6849f82c00847502fbd2194f7ad460b136f513

**Comment by bryanculver** [comment]
Closed with #3483
