### ISSUE TITLE
IPAM Overhaul: Network Namespace

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3244]
```[tasklist]
### TODO
- [x] #3245
- [x] #3337
- [x] #3429
- [ ] #3681
- [ ] https://github.com/nautobot/nautobot/issues/4097
- [ ] https://github.com/nautobot/nautobot/issues/4098
- [ ] https://github.com/nautobot/nautobot/issues/4225
- [ ] #3682
- [ ] #3683
- [ ] #3684
- [ ] #3685
- [ ] #3686
- [ ] #3687
- [ ] #3688
- [ ] #3689
- [ ] #3690
```

```[tasklist]
### Stretch
- [ ] Overriding `name` on `VRFDeviceAssignment`: overlapping `VRF` names in different namespaces should not be possible
- [ ] UI for Overriding `rd` on `VRFDeviceAssignment`
```

---

### As ...

Nelly - Network Engineer

### I want ...

To have a model which defines a uniqueness boundary for IPAM data models

### So that ...

I can better track the relationships in the data

### I know this is done when...

- Create a flat model to specify the name of a network namespace
- Prefix, VLAN Group, VLAN, & VRF should all have relationships to a namespace
  - This relationship forms the boundary for uniqueness constraints
  - This relationship should be optional

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)
