### ISSUE TITLE
Epic: Dynamic Group Enancements

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3268]
We implemented a 1.0 version of Dynamic Groups in 1.3, and Groups of Dynamic Groups (effectively a 2.0) in 1.4.

Here we track a collection of enhancements, both for performance and usability, for Dynamic Groups.

```[tasklist]
### Performance
- [ ] https://github.com/nautobot/nautobot/issues/3269
- [ ] https://github.com/nautobot/nautobot/issues/3270
- [ ] Implement a fully-revsible query from device to determine which group it is a part of
- [ ] Add support for "hidden" dynamic groups that are lazy-evaluated (only upon asking, not in list view)
```

```[tasklist]
### Adoption
- [ ] https://github.com/nautobot/nautobot/issues/1822
- [ ] #2782 
- [ ] Config Contexts uses DG for Definition
- [ ] Filter List Views by DG Membership
- [ ] https://github.com/nautobot/nautobot/issues/3271
- [ ] https://github.com/nautobot/nautobot/issues/3765
```

```[tasklist]
### Overhaul
- [ ] Dynamic Group hierarchy should be modeled as graphs
```

**Comment by itdependsnetworks** [comment]
Are all content types going to be included?

**Comment by bryanculver** [comment]
> Are all content types going to be included?

Issue #1822 has been added under "Adoption", still waiting on more of #1483 to be completed.

@itdependsnetworks Please throw some comments into #1822 for models you'd like to see sooner rather than later so that maybe we can get them merged in sooner rather than later. Since adding new model support is not a breaking change they can come in any release but their pre-requisites (cleaning up the Filtersets) must be completed in 2.0.

**Comment by jathanism** [comment]
Should we track #1483 as a dependency under **Adoption** here since it's relevant as a blocker to #1822? IMO yes, but I'll leave it to you @bryanculver .

**Comment by bryanculver** [comment]
> Should we track #1483 as a dependency under **Adoption** here since it's relevant as a blocker to #1822? IMO yes, but I'll leave it to you @bryanculver .

I think it's sufficiently described inside #1483 and #1822 as the blocking relationship (and the fact that #1737 is at the root of the blocking).

**Comment by itdependsnetworks** [comment]
* Circuits
* Interfaces
* Locations
* Aggregate / Whatever IPAM considerations based on design changes.

**Comment by EdificomSA** [comment]
Is there a way to use filter query logic on devices to partial match/regexp by name in a dynamic group ? I tried with ic__match and .*match.* and re'.*match.*' without success

**Comment by bryanculver** [comment]
> Is there a way to use filter query logic on devices to partial match/regexp by name in a dynamic group ? I tried with ic__match and ._match._ and re'._match._' without success

You'll need to see if a filter supports regular expression: https://github.com/nautobot/nautobot/issues/1525, https://docs.nautobot.com/projects/core/en/stable/rest-api/filtering/#string-fields Not all fields do.

**Comment by lampwins** [comment]
Closing this out in favor of targeted stories.
