### ISSUE TITLE
Remove `Aggregate` Model, Move to `Prefix`

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3302]
Follow-on from #1362.

## TODO
- [ ] Remove Aggregate model and migrate any existing instances to Prefix containers
  - [ ] `network`/`broadcast`/`prefix_length`/`tenant`/`description` copied over to `Prefix`
  - [ ] `rir` -> Nullable FK from Prefix
  - [ ] `date_added` -> `date_allocated` Optional DateTimeField

**Comment by bryanculver** [comment]
Closed with #3305
