### ISSUE TITLE
Job execution without ORM access

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3382]
### As ...

Patti - Platform Admin

### I want ...

A Job type which allows for execution on a worker node that does not have access to the DB (i.e. no ORM)

### So that ...

I can simplify the deployment and infrastructure requirements for distributed workers.

### I know this is done when...

- I can deploy a job worker which does not require me to provide that worker with the a direct connection to the Nautobot DB.
- I can write a job to be executed on such a worker that allows me to retrieve, create, and manipulate data in Nautobot.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
Also, I am not suggesting we change the way that all jobs work all of the time. There are any valid use cases for Jobs that perform complex business logic using the ORM that are either impossible or very hard to do via the REST API. Instead, I propose a type of jobs which supports an alternative operational method, which has use-case limitations, but offers a simpler infrastructure architecture.

**Comment by itdependsnetworks** [comment]
Not exactly the same, but in line with simplification of jobs I will point out this comment to remove/limit logging when it doesn't matter. https://github.com/nautobot/nautobot/issues/765#issuecomment-1272388605

**Comment by lampwins** [comment]
Such jobs should still be able to run on "traditional" celery workers.

**Comment by gsnider2195** [comment]
## Design meeting notes

We would need to determine how to securely transfer the API key. Without access to the database, the worker will only be able to communicate with the server through the message broker (redis) until the API connection is established. Redis by default probably isn't suitable for transferring API keys. One option as a temporary stopgap would be to require the API key to be created in advance and loaded on the worker as an environment variable.

We may also need to set an environment variable on the worker for the REST API url because 1) django doesn't give a good api for retrieving your full url path and 2) remote workers may need to access the nautobot server from a different url than the rest of the users, for example if you need to hit a natted IP address.

In order to manage the state of job results we need to:
- Pass an API key that can be used to change the job result (probably a requirement in general for this issue)
- Hook into a celery signal or one of the special task methods (possibly `BaseJob.before_start`) to know when to progress the status from `Pending` to `Started`
- Use the `BaseJob.on_failure` method to progress the `JobResult` status to `Failure`
- Use the `BaseJob.on_success` method to progress the `JobResult` status to `Success`

`JobLogEntry` will need PATCH, POST, PUT, and DELETE REST API endpoints.

`JobResult` will need PATCH, POST, and PUT REST API endpoints.

### Worker startup

Current worker gets its settings from the nautobot config. We'll need to supply those to the standalone worker somehow. The default is a `celeryconfig.py` in the `PYTHONPATH`. We tested creating a worker using just `celery worker` on a server with a `celeryconfig.py` with `broker_url = "redis://:password@redis:6379/0"` and it was able to load and join the queue but when we tried a `nautobot-server celery inspect report` from the nautobot web server we got the following error, indicating we need some more of the nautobot celery config to be bootstrapped on the worker (specifically the serializer in this case):

```
[2024-03-26 16:38:06,348: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)') [type:'application/x-nautobot-json' encoding:'utf-8' headers:{'clock': 1, 'expires': 1711471087.3451312}]

body: b'{"method": "ping", "arguments": {}, "destination": ["celery@"], "pattern": null, "matcher": null, "ticket": "3d4f4527-e815-46ad-86d1-f0a07dfe0fbe", "reply_to": {"exchange": "reply.celery.pidbox", "routing_key": "0db76f82-8c3b-39e0-a1f4-b0f8b1bc5741"}}' (251b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
    decoded = None if on_m else message.decode()
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
    self._decoded_cache = self._decode()
                          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
    return loads(self.body, self.content_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)
[2024-03-26 16:39:12,061: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)') [type:'application/x-nautobot-json' encoding:'utf-8' headers:{'clock': 1, 'expires': 1711471153.0572736}]

body: b'{"method": "ping", "arguments": {}, "destination": ["celery@"], "pattern": null, "matcher": null, "ticket": "0adaadb2-8431-4e88-b9c2-a17fbfb6d44f", "reply_to": {"exchange": "reply.celery.pidbox", "routing_key": "65b1b646-d4b8-33ea-a409-a09b4524ab79"}}' (251b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
    decoded = None if on_m else message.decode()
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
    self._decoded_cache = self._decode()
                          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
    return loads(self.body, self.content_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)
[2024-03-26 16:39:18,391: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)') [type:'application/x-nautobot-json' encoding:'utf-8' headers:{'clock': 1, 'expires': 1711471159.3880951}]

body: b'{"method": "report", "arguments": {}, "destination": null, "pattern": null, "matcher": null, "ticket": "06da73c3-aaa2-427f-a1e2-fdab3826a9ae", "reply_to": {"exchange": "reply.celery.pidbox", "routing_key": "d1395a66-2c13-3042-ab2d-6b0171b3c0a8"}}' (246b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
    decoded = None if on_m else message.decode()
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
    self._decoded_cache = self._decode()
                          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
    return loads(self.body, self.content_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type application/x-nautobot-json (application/x-nautobot-json)
```

### TODO

- Create settings/env vars for the worker's API key and the Nautobot REST API url
- Create a cli command to load the nautobot custom celery serializer and any other required nautobot bootstrap code (probably the full nautobot config and the env vars above) before continuing to load the default celery worker
- Add PATCH, POST, PUT, and DELETE REST API endpoints to `JobLogEntry`
- Add PATCH, POST, and PUT REST API endpoints to `JobResult`
- Update `BaseJob` methods with the state management code proposed earlier in this comment
- See if it works?

**Comment by itdependsnetworks** [comment]
I would advocate to not spend time on this. This misses the root of the challenges that we have. Our challenges are in managing the remote infrastructure, while it's true you should have to manage it less, it is not clear if that is a good thing. At least while everything has to be the same, it will fail early and fail often.

No matter what, we still need to manage the remote infrastructure, and this does not solve that problem, and potentially exacerbates the underlying remote worker challenge.
