### ISSUE TITLE
IPAddress: Addresss `host` modifiable, `broadcast`, `prefix_length` removal

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3465]
See #1673 for context.

```[tasklist]
### Tasks
- [x] Make `host` not modifiable
- [x] Remove `broadcast`
- [x] Rename `prefix_length` to `mask_length`
- [ ] ~~`mask_length`, which is currently a derived attribute from `prefix_length`, should now be set at `IPAddressToInterface` M2M instance. (Suggest a default value for `mask_length` from the parent prefix's `prefix_length`. )~~
```

**Other:**
Data migrations: #3681
Unit tests: #3688

**Comment by bryanculver** [comment]
For 2.0.0: Must remove the fields above. `host` modifiable may be easy enough to enforce in the clean method for now, but not required for 2.0.0.

**Comment by HanlinMiao** [comment]
Closed by #3842
