### ISSUE TITLE
Restrict access to what a user sees when not logged into Nautobot

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#3646]
```[tasklist]
### TODO
- [ ] When `HIDE_RESTRICTED_UI` is enabled and a user is not logged in, all routes lead to the login page
- [ ] When `HIDE_RESTRICTED_UI` is enabled and a user is not logged in, the footer only contains the current time (remove hostname, links)
- [ ] When `HIDE_RESTRICTED_UI` is enabled and a user is not logged in, navigating to the browsable API, Swagger, and GraphQL pages redirects to the login page
- [ ] When `HIDE_RESTRICTED_UI` is enabled and a user is not logged in, banners (except for LOGIN_BANNER) are not displayed
```
---
### As ...

Patti - Platform Admin

### I want ...

to restrict what a user can see when not logged into Nautobot to improve the security of the platform. 

### So that ...

I am able to confidently expose Nautobot in a large organization or even on the Internet without users knowing more details than they need to know (even giving the option to the Nautobot identity when not logged in).

### I know this is done when...

- [ ] There is an option remove the footer and/or individually (a) the "hostname" that is displayed in the bottom left (given "nautobot" may be used in the name quite often) and (b) Not show Theme, Docs, API, GraphQL, Code, and Help.  This removes some of the "Nautobot identity" when not logged in. 
- [ ] Ensure API docs are now browsable when not logged in.  For one, it gives the identity of the application, but it also exposes which plugins/Apps are installed without logging in. 
- [ ] Ensure GraphiQL is not available for users not logged in.  I just tested in the demo.nautobot.com sandbox and I tried a valid devices query when not logged in and I got a valid response with an empty list as a result.  It _seems_ like I got a 200 and I'd _at least_ expect a 400. Regardless, this is proposing not viewing GraphiQL when not logged. 
- [ ] Do not display top and bottom banners when not logged in (not the login banner)
- [ ] ~Remove the Nautobot logo (in the top left) when not logged in.~ (willing to discuss, but not doing for now)
- [ ] Remove the search bar in top right.
- [ ] ~I have the option to ONLY see a Login panel with username and password and the timestamp in the footer (at best).~ (HIDE_RESTRICTED_UI covers this for as far as we are going to go with it)

~Each of these can be its own configurable option or they can be wrapped into larger and more "secure mode".  It may make sense to wrap all of them up, but keep the logo as its own option.~ All of this will be based on setting `HIDE_RESTRICTED_UI=True`.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

N/A

---

**Comment by lampwins** [comment]
I can agree with pretty much everything, except `Remove the Nautobot logo (in the top left) when not logged in.` What about the HTML page title, or the favicon? See my comment on #3732

**Comment by jedelman8** [comment]
My thought was similar to the final message there from @MeganerdDev 

I think this won't be the case with the switch to what is being discussed, but the new link of toggling between old and new UIs should be in scope too.

**Comment by glennmatthews** [comment]
Implemented by #4068 for 1.6.
