### ISSUE TITLE
IPAM Overhaul: Data Migration for Namespace, VRF, Prefix, IP Address

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3681]
Data migrations for the changes introduced in #1032, #3244, #2915, #1673, and #2403

Plan doc: https://github.com/nautobot/nautobot/wiki/2.0:-IPAM-Overhaul-Data-Migration-Plan

```[tasklist]
### TODO
- [x] Merge `next` into prototype branch
- [x] Ensure tests are passing (note that many IPAM related ones are commented out, pending #3682, #3683)
- [x] Ensure first `Namespace` is created
- [x] Write `VRF` migrations
- [x] Write `Prefix` migrations
- [x] Write `IPAddress` migrations
```

**Comment by bryanculver** [comment]
Closed with #3378
