### ISSUE TITLE
UI Overhaul: Sprint 50 Hackathon

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3691]
```[tasklist]
### Tasks
- [x] Make detail view look like Figma design @bryanculver @HanlinMiao
- [x] Pull tab data from API @HanlinMiao
- [x] Make list view look like Figma design @timizuoebideri1
- [x] Move all view slug URLs to PK URLs @gsnider2195
- [x] Polish up Detail endpoint @HanlinMiao
- [x] Pagination @HanlinMiao
- [x] Improve accordion UX @glennmatthews
- [x] Create homepage view @glennmatthews
- [x] Default columns for list view (defined on model) @jathanism
- [x] Improve home view loading performance @gsnider2195
- [x] Find something plugin-centric to be included into the UI @glennmatthews
- [ ] Get edit view loading from an API-provided schema @jathanism
- [x] Improve home view grid and styling
- [x] Move `depth=0` API to return walkable response (hyperlink) @glennmatthews #3679
- [x] **nautobot-ui**: Fix horizontal scrolling going off the view not working for non-Firefox browsers @norbert-mieczkowski-codilime
- [ ] **nautobot-ui**: Fixed columns (checkbox, name?, action menu) @norbert-mieczkowski-codilime
- [ ] Move all queries over to RTK pattern (POST + invalidate GET) @bryanculver
- [x] Cache/local storage quirks
- [ ] Remove M2M fields from `depth=0` response @glennmatthews #3702
```
