### ISSUE TITLE
2.0 Pre-Migration Helpers

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3747]
### Proposed Changes

Introduce and document a collection of pre-migration helpers to inform installers that they will likely incur migration failures. Could be one of, or a collection of, strategies:

- System checks
- "Check" migration
- Management commands
- Job(s)

### Justification

```[tasklist]
### Tasks
- [ ] https://github.com/nautobot/nautobot/issues/3937
- [ ] https://github.com/nautobot/nautobot/issues/4247
- [ ] #3287
- [ ] #3372
- [ ] https://github.com/nautobot/nautobot/issues/4316
```

**Comment by bryanculver** [comment]
Only two committed pre-migration helpers exist and are in the milestone. Closing epic.
