### ISSUE TITLE
Audit natural key fields for all models

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3752]
After #3423, Nautobot's data models almost all have natural keys, most of which are derived automatically from the `unique` or `unique_together` settings on each model. As a sanity measure after completing #2908 and #2909, but before releasing 2.0.0, we should audit the natural-key fields for every model and make sure they are the most appropriate set of fields to use as a natural key. Among other considerations:

- a single `unique=True` field cannot be the natural key by itself if it is also `null=True`, so in such a case a composite natural key needs to be identified and explicitly specified in the model definition
- in cases where a model has multiple `unique_together` constraints, the first such constraint may not in fact be the most logically appropriate natural key, especially if any of its components are `null=True` (are we seeing a pattern here?)
```[tasklist]
### Tasks
- [ ] https://github.com/nautobot/nautobot/issues/3972
- [ ] https://github.com/nautobot/nautobot/issues/3973
- [ ] https://github.com/nautobot/nautobot/issues/3974
- [ ] https://github.com/nautobot/nautobot/issues/3975
- [ ] https://github.com/nautobot/nautobot/issues/3976
- [ ] https://github.com/nautobot/nautobot/issues/3977
```

**Comment by bryanculver** [comment]
Someone can condense the natural key fields for all models into a simple spreadsheet to review then we can discuss them dogpile-style as to if they are the best fields or not.

**Comment by glennmatthews** [comment]
| Model | natural_key_fields | Comments |
| - | - | - |
| circuits.Circuit | | |
| circuits.CircuitTermination | | |
| circuits.CircuitType | | |
| circuits.Provider | | |
| circuits.ProviderNetwork | | |
| dcim.Cable | | |
| dcim.CablePath | | |
| dcim.ConsolePort | | |
| dcim.ConsolePortTemplate | | |
| dcim.ConsoleServerPort | | |
| dcim.ConsoleServerPortTemplate | | |
| dcim.Device | | |
| dcim.DeviceBay | | |
| dcim.DeviceBayTemplate | | |
| dcim.DeviceRedundancyGroup | | |
| dcim.DeviceType | | |
| dcim.FrontPort | | |
| dcim.FrontPortTemplate | | |
| dcim.Interface | | |
| dcim.InterfaceTemplate | | |
| dcim.InventoryItem | | |
| dcim.Location | | |
| dcim.LocationType | | |
| dcim.Manufacturer | | |
| dcim.Platform | | |
| dcim.PowerFeed | | |
| dcim.PowerOutlet | | |
| dcim.PowerOutletTemplate | | |
| dcim.PowerPanel | | |
| dcim.PowerPort | | |
| dcim.PowerPortTemplate | | |
| dcim.Rack | | |
| dcim.RackGroup | | |
| dcim.RackReservation | | |
| dcim.RearPort | | |
| dcim.RearPortTemplate | | |
| dcim.VirtualChassis | | |
| extras.ComputedField | | |
| extras.ConfigContext | | |
| extras.ConfigContextSchema | | |
| extras.CustomField | | |
| extras.CustomFieldChoice | | |
| extras.CustomLink | | |
| extras.DynamicGroup | | |
| extras.DynamicGroupMembership | | |
| extras.ExportTemplate | | |
| extras.FileAttachment | | |
| extras.FileProxy | | |
| extras.GitRepository | | |
| extras.GraphQLQuery | | |
| extras.HealthCheckTestModel | | |
| extras.ImageAttachment | | |
| extras.Job | | |
| extras.JobButton | | |
| extras.JobHook | | |
| extras.JobLogEntry | | |
| extras.JobResult | | |
| extras.Note | | |
| extras.ObjectChange | | |
| extras.Relationship | | |
| extras.RelationshipAssociation | | |
| extras.Role | | |
| extras.ScheduledJob | | |
| extras.ScheduledJobs | | |
| extras.Secret | | |
| extras.SecretsGroup | | |
| extras.SecretsGroupAssociation | | |
| extras.Status | | |
| extras.Tag | | |
| extras.TaggedItem | | |
| extras.Webhook | | |
| ipam.IPAddress | | |
| ipam.IPAddressToInterface | | |
| ipam.Namespace | | |
| ipam.Prefix | | |
| ipam.RIR | | |
| ipam.RouteTarget | | |
| ipam.Service | | |
| ipam.VLAN | | |
| ipam.VLANGroup | | |
| ipam.VRF | | |
| ipam.VRFDeviceAssignment | | |
| ipam.VRFPrefixAssignment | | |
| tenancy.Tenant | | |
| tenancy.TenantGroup | | |
| users.AdminGroup | | |
| users.ObjectPermission | | | 
| users.Token | | |
| users.User | | |
| virtualization.Cluster | | |
| virtualization.ClusterGroup | | |
| virtualization.ClusterType | | |
| virtualization.VMInterface | | |
| virtualization.VirtualMachine | | |

**Comment by glennmatthews** [comment]
Action plan:

- [ ] Change Cable natural-key to simply `pk` as this is one of the rare cases where the PK is a user-facing identifier for the model.
- [ ] Change natural-keys for CablePath and TaggedItem to `pk` as these are not user-facing models
- [ ] Change natural-key for ObjectChange to `pk` for simplicity
- [ ] Change natural-key for Token to `pk`
- [ ] Implement variadic natural-key for InventoryItem
- [ ] Add `rack, units` natural-key for RackReservation
- [ ] VirtualChassis natural-key should just be `name`
- [ ] Change natural-key for ComputedField and Relationship to `key`
- [ ] Investigate feasibility of using `prefix` instead of `network, prefix_length` for Prefix
- [ ] Investigate UI/UX around object import failures due to non-unique object references (e.g. importing Interfaces where there are multiple Devices with null `name`)
- [ ] Investigate UI/UX around referencing related objects by UUID in CSV import when a natural-key exists (supported by REST serializers, may not be supported by CSV parser at present)

**Comment by bryanculver** [comment]
Major kudos to @glennmatthews for championing the move to natural keys. Only issue remaining is #3975 which has a clear path to completion.
