### ISSUE TITLE
2.0 Documentation: Migrating Jobs

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3940]
### Proposed Changes

For authors of 1.X Jobs, how to I migrate them to 2.X Jobs.

```[tasklist]
### Tasks
- [ ] Change in registration pattern
- [ ] Change in the function signature
- [ ] Change logging functionality
- [ ] Update examples and relevant documentation for #1622
- [ ] Link to examples for implementing atomic functionality
- [ ] Add an entry to the 2.0 Release Overview docs summarizing the Job changes.
- [ ] Make sure to call out that `super()` must be called in `Job.after_return()` in order for chords to work
```

**Comment by bryanculver** [comment]
Closed with #4032
