### ISSUE TITLE
Refine Device View in New UI

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4013]
Mockup:

![Device](https://github.com/nautobot/nautobot/assets/31187/b931280f-b814-4a71-8007-4c82afc7ed5f)

```[tasklist]
### Tasks
- [ ] Re-establishing the advanced tab into the base page layout
- [ ] Finish actions menu (expands to an Edit link to the legacy UI for the time being)
- [ ] Page sections are dummy data at preset, sections and fields as defined below:
```

Out Of Scope:

- Copy button does not need to be implemented
- Related model tabs (Interfaces, Relationships, Dynamic Groups) are out of scope for this issue

## Panel Breakdown (Detail Tab)
Each immediate bullet under LEFT and RIGHT are their own `<Panel>`s
- **LEFT**
    - Device: Key-value panel, fields in legacy UI
    - Management: Key-value panel, fields in the legacy UI
- **RIGHT** 
    - Tags: Empty panel just listing out tags (similar to how they are display in the new UI today)
    - Relationships: Key-value panel
    - Comment: Empty panel with the rendered comment box

## Panel Breakdown (Advanced Tab)
- **LEFT**
    - Metadata: Key-value panel, fields in legacy UI (created, updated, UUID)

**Comment by bryanculver** [comment]
![Page Title Bar](https://github.com/nautobot/nautobot/assets/31187/84c83a36-37ea-43e9-9218-a370701010c1)
---
![Panels](https://github.com/nautobot/nautobot/assets/31187/28bc72b5-1849-4720-9693-dae15c1fdbde)
---
![Page Tabs](https://github.com/nautobot/nautobot/assets/31187/31df8be5-98ec-45d1-9a91-e00ae913648c)

**Comment by HanlinMiao** [comment]
Closed by #4233
