### ISSUE TITLE
Add new model checklist to the docs

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5189]
See the checklist on PR #5137 for an example of the tasks involved.  We might want to just add to `nautobot/docs/development/apps/api/models/index.md`

============ EDIT ===============

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Create $NEWMODEL model
  - [ ] Migrations
  - [ ] Default statuses (data migration)
  - [ ] Serializer
  - [ ] List view / Table
  - [ ] Create/edit form
  - [ ] Create/edit view
  - [ ] Bulk edit form
  - [ ] Bulk edit view
  - [ ] Filterset
  - [ ] Filter form
  - [ ] Factory
  - [ ] Unit tests
  - [ ] Documentation
  - [ ] Add to homepage
  - [ ] ConfigContext
  - [ ] extra_features
  - [ ] extra_features documentation
  - [ ] Update nautobot.apps
  - [ ] Add to global search
- [ ] Add FK from $NEWMODEL to $EXISTINGMODEL
  - [ ] Migration
  - [ ] Model validation (device type must match softwareimage and device)
  - [ ] Update querysets (select_related)
  - [ ] Serializer
  - [ ] Create/edit form
  - [ ] Create/edit view
  - [ ] Bulk edit form
  - [ ] Bulk edit view
  - [ ] Device detail view
  - [ ] $EXISTINGMODEL detail view
  - [ ] Filterset
  - [ ] Filter form
  - [ ] Factory
  - [ ] Unit tests
  - [ ] Documentation
- [ ] Add m2m from $NEWMODEL to $EXISTINGMODEL
  - [ ] Migration
  - [ ] Model validation
  - [ ] Update querysets (prefetch_related)
  - [ ] Serializer
  - [ ] Expose through table in API
    - [ ] Serializer
    - [ ] Filterset
    - [ ] Viewset
    - [ ] Tests
  - [ ] Create/edit form
  - [ ] Create/edit view
  - [ ] Bulk edit form
  - [ ] Bulk edit view
  - [ ] DeviceType detail view
  - [ ] $EXISTINGMODEL detail view
  - [ ] Filterset
  - [ ] Filter form
  - [ ] Factory
  - [ ] Unit tests
  - [ ] Documentation
  - [ ] Update nautobot.apps
- [ ] Release overview documentation
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

**Comment by gsnider2195** [comment]
Missed in #5137: Add new models to the homepage

**Comment by gsnider2195** [comment]
This document should include detailed descriptions of the `extras_features` decorator options and when to use each of them vs when not to use them.

**Comment by gsnider2195** [comment]
Another thing that was missed, add a foreign key to the model from ConfigContext if the model would be relevant for making configuration decisions. If so, also update ConfigContextQuerySet, ConfigContextFilterSet, ConfigContext forms, edit and detail views and html templates,

**Comment by gsnider2195** [comment]
Add model to the global search

**Comment by itdependsnetworks** [comment]
Updated initial comment and adjusted to be slightly more generic for ease of access.

**Comment by glennmatthews** [comment]
Would be terrific to also create an additional PR template specifically for use with new-model PRs.
