### ISSUE TITLE
2.3 new features: Feedback from Sprint review

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5937]
Will open separate issues for these after grooming:

```[tasklist]
### Tasks
- [ ] Cloud accounts is shown in multiple places on the manufacturer detail view ![image](https://github.com/user-attachments/assets/bc6767fa-402d-4721-a5f9-665ca0d284bf)
- [ ] Review the new model checklist for all of the cloud models to verify all of the checklist items are completed and to update the checklist for updated or incorrect data
- [x] Bulk Actions button is not consistent with the primary actions button (potentially change bulk actions to primary button) #5952 ![image](https://github.com/user-attachments/assets/2646ec65-b33c-463d-86de-cc758de7874a)
- [ ] Scoped fields in Object Metadata tab is rendered json, should be updated to be more user friendly (`<ul>` maybe)
- [ ] Ensure the docs for ObjectMetadata explicitly states that there is currently no create/edit view in the UI for these models and they must be updated through the REST API
- [ ] Remove delete/bulk delete button from ObjectMetadata list view and corresponding table
```
