### ISSUE TITLE
Upgrade OpenAPI/Swagger support to OpenAPI 3.0

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#595]
### Proposed Changes

We currently support parts of OpenAPI 2.0, but incompletely, using [`drf-yasg`](https://github.com/axnsan12/drf-yasg). This project, however, is no longer actively maintained so aside from being forked, will never move past OpenAPI 2.0 nor will it receive any more fixes.

Plain and simple: I propose that we upgrade to support OpenAPI 3.0. To get there we must drop `drf-yasg` and replace it with [`drf-spectacular`](https://github.com/tfranzel/drf-spectacular). 

### Justification

But why? There is [demand for it from the community](https://github.com/nautobot/nautobot/issues/40), and per the `drf-yasg` documentation:

> If you are looking to add Swagger/OpenAPI support to a new project you might want to take a look at drf-spectacular, which is an actively maintained new library that shares most of the goals of this project, while working with OpenAPI 3.0 schemas.
> 
> OpenAPI 3.0 provides a lot more flexibility than 2.0 in the types of API that can be described. drf-yasg is unlikely to soon, if ever, get support for OpenAPI 3.0.

Automatic enumeration of a typed API is a thing of beauty. OpenAPI 3.0 brings this to the next level. Additionally, OpenAPI 3.0 is already years old and in fact there's [OpenAPI 3.1 out](https://stoplight.io/blog/difference-between-open-v2-v3-v31/#differences-between-openapi-3.0-and-3.1), but we have to start somewhere.

References:
- https://blog.readme.com/an-example-filled-guide-to-swagger-3-2/
- https://stoplight.io/blog/difference-between-open-v2-v3-v31/

### TODO

- [x] Investigate potential breaking changes going to 3.0
- [x] Investigate housekeeping/work needed to get schemas to generate in 3.0
  - [x] Identify if/which housekeeping are required to switch to 3.0, others remaining to future housekeeping
- [x] Complete housekeeping from above
- [x] Identify previously blocked enhancements awaiting 3.0

**Comment by glennmatthews** [comment]
Dropping `drf-yasg` as a dependency may potentially impact any plugins that are using drf-yasg's decorators and types to make their own API specification more accurate. In the 1.x timeframe, we will likely want to continue to include `drf-yasg` as a packaging dependency so that plugins don't suddenly start getting ImportErrors, even though we won't be using it in core any more. In 2.0 we can drop drf-yasg from our dependencies entirely.

**Comment by glennmatthews** [comment]
Fixes/enhancements that we can pursue after making this migration:
- #40
- #369
- #685 
- #1294 
- #1422 
- versioned OpenAPI documentation (e.g. being able to render the 1.2 or 1.3 schemas differently on request)

**Comment by bryanculver** [comment]
Closed with #1544
