### ISSUE TITLE
Failure Tracking

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#6180]
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to easily surface data for objects that were attempted to be imported into Nautobot but failed due to missing information. For example, attempting to import a Device but missing DeviceType.

### So that ...

I can easily find information pertaining to data that was attempted to be imported but failed.

### I know this is done when...

I have a centralized location that contains all failure data that contains where the data came from, last time it was seen, any validations of the data, and all other relevant information that might assist in me in fixing the System of Record so the object can finish being imported.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [X] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

It would most likely require some DB changes.

**Comment by itdependsnetworks** [comment]
To me this would be data validation. You have #7676 open as well, which makes sense to keep open, but the data validation framework provides a centralized report and allow the user to have business logic to add to it. 

If I got that wrong, feel free to re-open.
