### ISSUE TITLE
v1.0.0 release checklist items

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#71]
### Proposed Changes

As per `docs/development/release-checklist.md`:

- [x] Update all Python dependencies to their latest patch versions
- [x] Update static dependencies:
  - [x] Bootstrap 3
  - [x] Material Design Icons
  - [x] Select2
  - [x] jQuery
  - [x] jQuery-UI
- [x] Add/update release notes
- [x] Update version number (`poetry version major`)

### Justification

Following a consistent release process.
