### ISSUE TITLE
Epic: Jobs Overhaul

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#765]
## Purpose

Jobs have grown significantly since they were introduced but now we're ready to help it achieve the next level of use cases in both scale and complexity.

## Plan

We look to address several key points with overhauling Jobs:
- Improve state management (currently we must keep tabs on Celery through `JobResult` which is error prone)
    - Lets hope to address things like: #633 
- Simplify APIs (better natural keys, simpler job scheduling, less "magic" methods)

## TODO

```[tasklist]
#### Data Model
- [x] #2611
- [x] https://github.com/nautobot/nautobot/issues/1622
- [x] https://github.com/nautobot/nautobot/issues/3856
```

```[tasklist]
#### Mechanics
- [x] #1622
- [x] https://github.com/nautobot/nautobot/issues/3453
- [x] #2979
- [x] https://github.com/nautobot/nautobot/issues/3692
```

```[tasklist]
#### Logging
- [x] #2331
```

```[tasklist]
### Bugs/Must Fix for 2.0
- [x] Fix `profile` feature (requires celery_kwargs field in job result)
- [x] Ensure scheduled jobs set the `user` when executing the job (Add `user` field to `ScheduledJob` or just leverage `celery_kwargs["user"]`?)
- [x] Update Job Hooks, Job Buttons to account for new enqueueing methods
```

```[tasklist]
### Housekeeping
- [x] https://github.com/nautobot/nautobot/issues/3713
- [ ] #2853
```

```[tasklist]
### Documentation
- [x] #3940
- [x] How to implement dry-run support in a new or existing job (including but not limited to `transaction.atomic()`)
```

### Elsewhere
- [ ] Client code and client documentation (e.g. `pynautobot` and `nautobot-ansible`) should be shored up for v2 changes
- [x] #4095
- [x] See about eliminating `scheduled_job_handler`, altho since that’s internal it’s less scary and may be able to live and could just be used as a dispatcher of a Job's Celery task

### Related
- #2980
- #2726
   - Done via not migrating it in #1622 (#3228)

### Follow-on
- [ ] https://github.com/nautobot/nautobot/issues/3440
- [ ] https://github.com/nautobot/nautobot/issues/3705
- [ ] #4238
- [ ] #4239
- [ ] #4240
- [x] https://github.com/nautobot/nautobot/issues/3928

---
_For those who have been keeping track this epic has been very long-lived and has been overhauled numerous times has we've continuously improved Jobs. Here on out we will be aiming to close out Epics per release cycle so this will continue to track our overhaul of Jobs for 2.0 and be closed then._

_For future enhancement plans for jobs, please see #2724 and #2725_

**Comment by itdependsnetworks** [comment]
Can we consider "job re-launch" or similar? Especially when testing jobs it can become tedious to have to reset the data each time for the job.

**Comment by bryanculver** [comment]
@lampwins Please groom.

**Comment by itdependsnetworks** [comment]
Point of consideration for Jobs. There is often times where you simply do not care about the job details to be retained over time, and as such do not require the logging to be saved. Take for example this recent conversation on separating NAPALM out. 

https://github.com/nautobot/nautobot/issues/2557#issuecomment-1267542555

The current implementation is `blocking`, however this is not a scalable solution. In theory we should break out to an async process, which would ideally use the jobs framework. That being said, we do not need to store the data, but simply need the initial responses and errors that may happen. 

So, succinctly:
* Would like the ability to have jobs without writing everything to the database.

**Comment by jifox** [comment]
Is there something like [Issue #2171](https://github.com/nautobot/nautobot/issues/2171) planned as an enhancement too?

**Comment by jathanism** [comment]
> Is there something like [Issue #2171](https://github.com/nautobot/nautobot/issues/2171) planned as an enhancement too?

That flew under my radar, and I don't think it's out of the realm of possibility for 2.x, but just not for 2.0.0 seeing as we already have a lot of complex work in flight.

**Comment by bryanculver** [comment]
Closing as the only remaining item is #2853, minor housekeeping. Kudos @nautobot/core!
