### ISSUE TITLE
Epic: Data Insights

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#766]
This is a larger issue to track several issues that will be opened up to increase visibility into the data stored in Nautobot. When they are opened, they will be linked and referenced accordingly:

- [ ] Create dashboards to simplify consumption of data already in Nautobot.  Pick 2 or 3 data models to start with to get feedback on the approach, e.g.  % of particular device types, % of circuit providers, etc. 

```[tasklist]
### Tasks
- [ ] https://github.com/nautobot/nautobot/issues/710
- [ ] https://github.com/nautobot/nautobot/issues/1629
- [ ] https://github.com/nautobot/nautobot/issues/4051
- [ ] https://github.com/nautobot/nautobot/issues/4053
- [ ] https://github.com/nautobot/nautobot/issues/4054
- [ ] https://github.com/nautobot/nautobot/issues/4065
```

**Comment by glennmatthews** [comment]
See #710 for worker/job metrics requirements.

**Comment by jedelman8** [comment]
#710 takes care of the first two items in this Epic.

**Comment by Kircheneer** [comment]
> Add functionality from the Capacity Metrics plugin into core

Is this a definitive plan?

**Comment by bryanculver** [comment]
> > Add functionality from the Capacity Metrics plugin into core
> 
> Is this a definitive plan?

It's the desire at the time but for now, this isn't committed in any significant way.

**Comment by Kircheneer** [comment]
For capacity-metrics -> core my thoughts are the following: 
- RQ functionality: Drop
- Model count stats: Transfer this to core, keeping in mind that in a multiprocess environment only one process needs to calculate these, as they are the same across all processes
- Metric extensibility: Capacity-metrics offers the tools for plugins to provide custom metrics - this needs some more thought

**Comment by lampwins** [comment]
Closing to focus on more concretely defined issues
