### ISSUE TITLE
Epic: Notes

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#767]
This is a larger issue to track several issues that will be opened up to add _notes_ to core models. When they are opened, they will be linked and referenced accordingly.

**Requirements:**
- [ ] Any BaseModel can have zero-to-many notes associated to it
- [ ] Notes should be able to support Markdown
- [ ] View lists of notes only associated to an individual object
- [ ] Editing existing notes
- [ ] Changelogging of notes

**Out of Scope:**
- No attachments in MVP
- No need for general purpose list/detail views for individual notes
- Bulk creation of notes

**TODO:**
- [ ] Design for Notes via API, GraphQL

**Comment by glennmatthews** [comment]
- [ ] Bulk-edit forms to allow the user to specify note text that would be applied (as distinct note records) to all edited objects (within a single content type, of course)

**Comment by bryanculver** [comment]
Closed with #1984
