### ISSUE TITLE
Epic: Core Data Model

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#768]
This is a larger issue to track several issues that will be opened up to enhance the core data model. When they are opened, they will be linked and referenced accordingly:

Custom Fields
- [x] Add JSON type for custom fields (#897)
- [x] Add support for "hidden" custom fields (#898)
- [ ] Add ability to apply custom fields to a subset of objects. Idea: Add ability to apply custom fields similar to config contexts (#889)
- [x] Add ability to "group" custom fields (#899)
- [ ] Improve UI to include "computed fields" simplifying UX for custom + computed fields being in two locations (#905)

General
- [x] #906
- [x] Generalize "roles." Add generic roles to be applied to "all" objects (similar to custom statuses)
- [ ] Add config contexts to _more_ models (#762)
- [x] Create "dynamic groups" with an object being able to be part of multiple groups (#896)

Plugin API

- [ ] Improve plugin API for model creation improving developer experience. Reference Django admin simplificity
- [ ] Bless and support ability to de-registration computed fields, custom fields, relationships in core that were created from plugins. Needs #16 

Reviews

- [ ] Explore extending filtering options for config contexts
- [ ] Explore integration of CFs and config contexts
- [ ] Explore _simplified_ way for creating new (basic) models, e.g. JSON Schema with config contexts

**Comment by glennmatthews** [comment]
- [ ] Dynamic / arbitrary groups of objects (within a single model/ content-type) - could be initially defined via queryset filters, but later extend to things like regex matching, etc.? See also #889.

**Comment by dgarros** [comment]
I've opened a new issue to track ` Generalize "roles." Add generic roles to be applied to "all" objects (similar to custom statuses)`
 https://github.com/nautobot/nautobot/issues/1063

**Comment by bryanculver** [comment]
@lampwins please groom.
