### ISSUE TITLE
Explore Simplified/Accelerated Plugin Development Experience

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#973]
This topic hints at a few other issues previously brought up, namely:

#928
#356
Related: #1569

### User Story

**As P.D. the Plugin Developer** I would like the easiest possible way to extend models
**I want to** be able to describe my model, and as little as possible 
**So that** my development efforts are minimal, and I can know that I am getting the latest capabilities. 
**I will know this is done when** when I can simply create a model (and potentially 1 or 2 more steps) and have all the views one would expect, including tables, forms, api's, UIs, etc. 

### Database Changes (Optional)

No

### External Dependencies (Optional)

No

Requirements

- [ ] Generic View classes https://github.com/nautobot/nautobot/issues/973#issuecomment-934400117
- [ ] Generic Forms, generated from models #1569
- [ ] Generic FilterForms, generated from models
- [ ] Generic FilterSets, generated from models #1483
- [ ] Generic Tables, generated from models
- [ ] Generic Navigation, generated from models. 

Out of Scope
- Changes to the DRF API framework

> Note: When stating `generated from models` it implies from the model, or a custom attribute, similar to the pattern derived from csv_headers.

**Comment by itdependsnetworks** [comment]
I have begun a POC on such a solution, and you can find here: https://github.com/nautobot/nautobot-plugin-golden-config/pull/138

**Comment by glennmatthews** [comment]
Thanks for the request. In addition to the discussion ongoing on your PR above, I'd just note that some of this also ties in to internal conversations we've had about in the longer term potentially replacing Nautobot's bespoke "generic" view classes with Django's own [generic view classes](https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/)

**Comment by itdependsnetworks** [comment]
We have made good and steady progress on this, don't need to keep this open.
